name: test
 
on:
  workflow_dispatch:
    inputs:
      message1:
        description: 'Parameter message'     
        required: true
        default: 'no message'
      tag1:
        description: 'Test scenario tags'
        required: false
 
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Message: ${{ github.event.inputs.message1 }}"
          echo "Tags: ${{ github.event.inputs.tag1 }}"
